"""add_latency_and_tokens

Revision ID: 23b55b974f5b
Revises: 4286f064dc9a
Create Date: 2026-08-17 11:38:59.516429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '23b55b974f5b'
down_revision: Union[str, Sequence[str], None] = '4286f064dc9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompt_records', sa.Column('latency_ms', sa.Integer(), nullable=True))
    op.add_column('prompt_records', sa.Column('total_tokens', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prompt_records', 'total_tokens')
    op.drop_column('prompt_records', 'latency_ms')
    # ### end Alembic commands ###
